config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'home', to: 'pages#home', as: 'home'
  get 'about', to: 'pages#about', as: 'about'
  get 'rabie', to: 'pages#Rabie', as: 'rabie'
  get 'new', to: 'pages#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # render 'home.html.erb'
  end
  def about
    # render 'about.html.erb'
  end
  def rabie
    # render 'rabie.html.erb'
  end
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ charset: 'utf-8' }
    %title Wapp
    %link{ href: '/application.css', rel: 'stylesheet', media: 'all' }
    %link{ href: '/favicon.png', rel: 'shortcut icon', type: 'image/png' }
  %body
    %h1 Wapp
    %script{ src: '/application.js', type: 'text/javascript' }

app/views/pages/about.html.erb
<h1>about</h1>
<p>
<%= link_to 'home', home_path %>
</p>

app/views/pages/home.html.erb
<h1>Welcome Back to shcool Man</h1>
<h2>Menu</h2>
<ul>
<li><%= link_to 'About', about_path %></li>
<li><%= link_to 'Rabie', rabie_path %></li>
</ul>

app/views/pages/new.html.erb
<p> Hello World this is branch2</p>

app/views/pages/rabie.html.erb
<h1>Rabie Mohamed</h1>
<p>
hello! this myy pages which is all ablot me
</p>
<p>
This my linkedin page <%= link_to 'https://www.linkedin.com/rabiemohamed','https://www.linkedin.com/rabiemohamed'%>
</p>
<%= image_tag("myimage.jpg") %>
<p>
<%= link_to 'Home',home_path %>
</p>